/* tslint:disable */
/* eslint-disable */
export const __wbg_get_spectrogramconfig_fft_size: (a: number) => number;
export const __wbg_get_spectrogramconfig_gain: (a: number) => number;
export const __wbg_get_spectrogramconfig_hop_length: (a: number) => number;
export const __wbg_get_spectrogramconfig_img_height: (a: number) => number;
export const __wbg_get_spectrogramconfig_img_width: (a: number) => number;
export const __wbg_get_spectrogramconfig_sample_rate: (a: number) => number;
export const __wbg_set_spectrogramconfig_fft_size: (a: number, b: number) => void;
export const __wbg_set_spectrogramconfig_gain: (a: number, b: number) => void;
export const __wbg_set_spectrogramconfig_hop_length: (a: number, b: number) => void;
export const __wbg_set_spectrogramconfig_img_height: (a: number, b: number) => void;
export const __wbg_set_spectrogramconfig_img_width: (a: number, b: number) => void;
export const __wbg_set_spectrogramconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_spectrogramconfig_free: (a: number, b: number) => void;
export const generate_spectrogram_image: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const spectrogramconfig_new: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const init_thread_pool: (a: number) => any;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const initThreadPool: (a: number) => any;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
